artifacts_roots: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL : https://github.com/GloryKO/cancer-image-folder/raw/main/cancerfolderone.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion